### ISSUE TITLE
frontend preparation

### ISSUE THREAD

**Issue by yasushisakai** [ohsugi/dove#12]
This might be a good start for making the front end.

https://github.com/yasushisakai/senatus/tree/blank

**Comment by ohsugi** [comment]
Exploring some templates and widgets, we could use:
 - https://github.com/lkrjangid1/Awesome-Flutter-Templates
 - https://www.fluttertemplates.dev/

Especially, the below would be the favorites:
 - https://github.com/abuanwar072/E-commerce-Complete-Flutter-UI
 - https://pub.dev/packages/syncfusion_flutter_maps
 - https://github.com/imaNNeo/fl_chart

Or combine simpler navigation snippets would be also attractive:
 - https://www.fluttertemplates.dev/widgets/forms/sign_in#responsive_sign_in
 - https://www.fluttertemplates.dev/templates/app-onboarding
 - https://www.fluttertemplates.dev/widgets/must_haves/profile_page
 - https://www.fluttertemplates.dev/widgets/must_haves/settings_page
 - https://www.fluttertemplates.dev/templates/dynamic_theme

**Comment by ohsugi** [comment]
Taken over with the below repo:
https://github.com/ohsugi/dove-frontend
