### ISSUE TITLE
Example of 'cross program invocation'

### ISSUE THREAD

**Issue by yasushisakai** [ohsugi/dove#6]
official docs showing how to make another program execute on behalf of a user(wallet)
https://docs.solana.com/developing/programming-model/calling-between-programs#program-signed-accounts

We see this in action here:

1. we first initialize an account using the callee program
https://github.com/yasushisakai/multisig-cpi/blob/main/tests/multisig-cpi.ts#L48

2. We want to edit this. We create the instruction to edit(update) here
https://github.com/yasushisakai/multisig-cpi/blob/4fb9ef6a7db8c96dc7ec93e96ae174e83261d51a/tests/multisig-cpi.ts#L66

3. and wrap it with a transaction using the caller(mutlisig) program.
https://github.com/yasushisakai/multisig-cpi/blob/4fb9ef6a7db8c96dc7ec93e96ae174e83261d51a/tests/multisig-cpi.ts#L75

4. we execute that transaction which is again implemented in the caller program
https://github.com/yasushisakai/multisig-cpi/blob/4fb9ef6a7db8c96dc7ec93e96ae174e83261d51a/tests/multisig-cpi.ts#L111

The 'executeTransaction' in consideration here is implemented here:

https://github.com/coral-xyz/multisig/blob/435d6eb15f10c9e99d81323890bc042cfcaa402f/programs/multisig/src/lib.rs#L186

**Comment by yasushisakai** [comment]
Looks like this modern explanation is better to understand CPI and PDAs.

https://www.anchor-lang.com/docs/cross-program-invocations

https://www.anchor-lang.com/docs/pdas

**Comment by yasushisakai** [comment]
https://github.com/yasushisakai/cpi_pda

**Comment by ohsugi** [comment]
Finally, I found the SOL transfer to the Project can be written without CPI and confirmed the program is correctly working by the [this update](https://github.com/ohsugi/dove/pull/42)
https://solanacookbook.com/references/programs.html#how-to-transfer-sol-in-a-program
